# Generated by Django 5.0.1 on 2024-03-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
