# Generated by Django 4.1.4 on 2022-12-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_auction_listing_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="description",
            field=models.CharField(default="exit", max_length=512),
            preserve_default=False,
        ),
    ]
