# Generated by Django 4.1.4 on 2022-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_auction_listing_bid_count_auction_listing_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="current_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
