# Generated by Django 4.1.4 on 2022-12-14 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_auction_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
