# Generated by Django 4.1.4 on 2022-12-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auction_listing_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="img",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
