# Generated by Django 4.1.4 on 2022-12-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auction_listing_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
