# Generated by Django 4.1.4 on 2022-12-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auction_listing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="img",
            field=models.CharField(max_length=256),
        ),
    ]
