# Generated by Django 4.1.4 on 2022-12-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="listing_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_listing",
                to="auctions.auction_listing",
            ),
            preserve_default=False,
        ),
    ]
