# Generated by Django 5.0.1 on 2024-05-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_categories_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
